[global]
parse_stroke_color = "-a stroke"
parse_individual_lines = "-a d -a points -a x1 -a x2 -a y1 -a y2"
page_sizes = ["Letter", "A4", "11x17 in", "A3", "17x23 in", "A2"]
letter_width = "8.5"
letter_height = "11"
a4_width = "8.3"
a4_height = "11.7"
11x17_width = "11"
11x17_height = "17"
a3_width = "11.17"
a3_height = "16.5"
17x23_width = "17"
17x23_height = "23"
a2_width = "16.5"
a2_height = "23.4"
postcards_width = "8"
postcards_height = "11.8"

[compose]
column_number = 1
row_number = 1
single_layer = 0    # radio button val
stroke_layers = 1   # radio button val
overwrite_color = 0
condense_color_layers = 1
layout = 1
layout_landscape = 1

[de_compose]
remove_placeholder = "e.g. 1, 3-5"

[process]
window_size = "555x870"
bbox = 0
bbox_xy = "0, 0"
crop = 0
crop_xy = "0, 0"
crop_wh = "0, 0"
scale = 1
center = 1
rotate_small = "90"
rotate_large = "0"
linemerge = 1
linemerge_tolerance = "0.0019685"
linesimplify_tolerance = "0.0019685"
linesort = 1
reloop = 1
squiggle = 0
squiggle_amp = "0.0196"
squiggle_period = "0.1181"
lineshuffle = 0
reverse = 0
reverse_flip = 0
layout = 1
layout_landscape = 1
crop_to_page_size = 1
multipass = "1"
linesimplify = 1
